
name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build -c --skip-tests
              env:
                  #Secrets for Files module testing
                  SHARED_KEY_OR_SAS_TOKEN: ${{ secrets.SHARED_KEY_OR_SAS_TOKEN }}
                  SECURE_CLIENT_PASSWORD: ${{ secrets.SECURE_CLIENT_PASSWORD }}
                  SECURE_CLIENT_CERT_PATH: ${{ secrets.SECURE_CLIENT_CERT_PATH }}
                  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
                  #Add blobs secrets names here
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      push
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
              